#!/bin/bash

POSTGRES=""

for var in "$@"
do
	if [ ${var} == "--help" ]
	then
		echo "runtests [PYTESTARGS]"
		echo "CALLS: pytest ./tests --ignore=./tests/skip --cov=./stream2segment [PYTESTARGS]"
		echo 
		echo "Example:"
		echo "DB_URL=postgresql://user:password@localhost/s2s_test ./runtests -x  --ignore=./tests/skip --cov=./stream2segment --cov-report=html"
		echo 
		echo "Notes: "
		echo "	DB_URL is a custom url to a database to be used (supported is postgres and sqlite)"
		echo "	If missing, it defaults to an in-memory sqlite database"
		echo "	If not missing, tests requiring a database will in any case run ALSO with an in-memory sqlite database"
		exit 0
	fi
done

if [ -n "$DB_URL" ]
then
	TMP_DB_URL="$DB_URL"
	unset DB_URL
	echo
	# set color to light blue:
	echo -e "\033[1;36mRunning db-tests with in-memory sqlite:\033[0m"
	echo temporarily unset DB_URL="$DB_URL"
	echo
	(pytest ./tests/functional/test_db.py \
		./tests/functional/test_download.py \
		./tests/functional/test_download2.py \
		./tests/functional/test_processing.py \
		./tests/functional/test_sqlevalexpr.py \
		./tests/functional/test_webgui.py \
		./tests/unit/test_dbqueries.py \
		./tests/unit/test_plotviews.py \
		./tests/unit/test_u_download.py "$@") ; \
	(echo ;\
		echo -e "\033[1;36mRunning all tests with postgres:\033[0m";\
		echo DB_URL="$TMP_DB_URL" pytest ./tests "$@";\
		echo ;\
		DB_URL="$TMP_DB_URL" pytest ./tests "$@")
else
	echo
	# set color to light blue:
	echo -e "\033[1;36mRunning all tests with in-memory sqlite:\033[0m"
	echo COMMAND: pytest ./tests --ignore=./tests/skip --cov=./stream2segment "$@"
	echo
	pytest ./tests "$@"
fi


